/**
 * generated by Xtext 2.18.0
 */
package org.xtext.ide;

import org.xtext.ide.AbstractMycnlIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MycnlIdeModule extends AbstractMycnlIdeModule {
}
