/**
 * generated by Xtext 2.18.0
 */
package org.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.MycnlRuntimeModule;
import org.xtext.MycnlStandaloneSetup;
import org.xtext.ide.MycnlIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MycnlIdeSetup extends MycnlStandaloneSetup {
  @Override
  public Injector createInjector() {
    MycnlRuntimeModule _mycnlRuntimeModule = new MycnlRuntimeModule();
    MycnlIdeModule _mycnlIdeModule = new MycnlIdeModule();
    return Guice.createInjector(Modules2.mixin(_mycnlRuntimeModule, _mycnlIdeModule));
  }
}
