/*
 * generated by Xtext 2.18.0
 */
package org.xtext.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.MycnlRuntimeModule
import org.xtext.MycnlStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MycnlIdeSetup extends MycnlStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MycnlRuntimeModule, new MycnlIdeModule))
	}
	
}
