/*
 * generated by Xtext 2.18.0
 */
package org.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.Fp.ui.internal.FpActivator;

public class MycnlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return FpActivator.getInstance().getInjector("org.xtext.Mycnl");
	}

}
