/**
 * generated by Xtext 2.18.0
 */
package org.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.ui.AbstractMycnlUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MycnlUiModule extends AbstractMycnlUiModule {
  public MycnlUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
