/**
 * generated by Xtext 2.18.0
 */
package org.xtext;

import org.xtext.AbstractMycnlRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MycnlRuntimeModule extends AbstractMycnlRuntimeModule {
}
