/*
 * generated by Xtext 2.18.0
 */
package org.xtext.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractMycnlScopeProvider extends XbaseBatchScopeProvider {
}
