/*
 * generated by Xtext 2.18.0
 */
package org.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.parser.antlr.internal.InternalMycnlParser;
import org.xtext.services.MycnlGrammarAccess;

public class MycnlParser extends AbstractAntlrParser {

	@Inject
	private MycnlGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMycnlParser createParser(XtextTokenStream stream) {
		return new InternalMycnlParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "DomainModel";
	}

	public MycnlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MycnlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
