/**
 * generated by Xtext 2.18.0
 */
package org.xtext.fp;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Design Commercial</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.fp.DesignCommercial#getNo_of_people <em>No of people</em>}</li>
 * </ul>
 *
 * @see org.xtext.fp.FpPackage#getDesignCommercial()
 * @model
 * @generated
 */
public interface DesignCommercial extends Query
{
  /**
   * Returns the value of the '<em><b>No of people</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>No of people</em>' attribute.
   * @see #setNo_of_people(int)
   * @see org.xtext.fp.FpPackage#getDesignCommercial_No_of_people()
   * @model
   * @generated
   */
  int getNo_of_people();

  /**
   * Sets the value of the '{@link org.xtext.fp.DesignCommercial#getNo_of_people <em>No of people</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>No of people</em>' attribute.
   * @see #getNo_of_people()
   * @generated
   */
  void setNo_of_people(int value);

} // DesignCommercial
