/**
 * generated by Xtext 2.18.0
 */
package org.xtext.fp;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>findtemp Create Lake</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.fp.findtempCreateLake#getArea <em>Area</em>}</li>
 * </ul>
 *
 * @see org.xtext.fp.FpPackage#getfindtempCreateLake()
 * @model
 * @generated
 */
public interface findtempCreateLake extends Query
{
  /**
   * Returns the value of the '<em><b>Area</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Area</em>' attribute.
   * @see #setArea(int)
   * @see org.xtext.fp.FpPackage#getfindtempCreateLake_Area()
   * @model
   * @generated
   */
  int getArea();

  /**
   * Sets the value of the '{@link org.xtext.fp.findtempCreateLake#getArea <em>Area</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Area</em>' attribute.
   * @see #getArea()
   * @generated
   */
  void setArea(int value);

} // findtempCreateLake
