/**
 * generated by Xtext 2.18.0
 */
package org.xtext.fp;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>findtemp Plant Trees</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.fp.findtempPlantTrees#getNo_of_trees <em>No of trees</em>}</li>
 * </ul>
 *
 * @see org.xtext.fp.FpPackage#getfindtempPlantTrees()
 * @model
 * @generated
 */
public interface findtempPlantTrees extends Query
{
  /**
   * Returns the value of the '<em><b>No of trees</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>No of trees</em>' attribute.
   * @see #setNo_of_trees(int)
   * @see org.xtext.fp.FpPackage#getfindtempPlantTrees_No_of_trees()
   * @model
   * @generated
   */
  int getNo_of_trees();

  /**
   * Sets the value of the '{@link org.xtext.fp.findtempPlantTrees#getNo_of_trees <em>No of trees</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>No of trees</em>' attribute.
   * @see #getNo_of_trees()
   * @generated
   */
  void setNo_of_trees(int value);

} // findtempPlantTrees
