/**
 * generated by Xtext 2.18.0
 */
package org.xtext.fp;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>findtemp Buil Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.fp.findtempBuilAction#getNo_of_buildings <em>No of buildings</em>}</li>
 *   <li>{@link org.xtext.fp.findtempBuilAction#getLength <em>Length</em>}</li>
 *   <li>{@link org.xtext.fp.findtempBuilAction#getBreadth <em>Breadth</em>}</li>
 *   <li>{@link org.xtext.fp.findtempBuilAction#getHeight <em>Height</em>}</li>
 * </ul>
 *
 * @see org.xtext.fp.FpPackage#getfindtempBuilAction()
 * @model
 * @generated
 */
public interface findtempBuilAction extends Query
{
  /**
   * Returns the value of the '<em><b>No of buildings</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>No of buildings</em>' attribute.
   * @see #setNo_of_buildings(int)
   * @see org.xtext.fp.FpPackage#getfindtempBuilAction_No_of_buildings()
   * @model
   * @generated
   */
  int getNo_of_buildings();

  /**
   * Sets the value of the '{@link org.xtext.fp.findtempBuilAction#getNo_of_buildings <em>No of buildings</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>No of buildings</em>' attribute.
   * @see #getNo_of_buildings()
   * @generated
   */
  void setNo_of_buildings(int value);

  /**
   * Returns the value of the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Length</em>' attribute.
   * @see #setLength(int)
   * @see org.xtext.fp.FpPackage#getfindtempBuilAction_Length()
   * @model
   * @generated
   */
  int getLength();

  /**
   * Sets the value of the '{@link org.xtext.fp.findtempBuilAction#getLength <em>Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Length</em>' attribute.
   * @see #getLength()
   * @generated
   */
  void setLength(int value);

  /**
   * Returns the value of the '<em><b>Breadth</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Breadth</em>' attribute.
   * @see #setBreadth(int)
   * @see org.xtext.fp.FpPackage#getfindtempBuilAction_Breadth()
   * @model
   * @generated
   */
  int getBreadth();

  /**
   * Sets the value of the '{@link org.xtext.fp.findtempBuilAction#getBreadth <em>Breadth</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Breadth</em>' attribute.
   * @see #getBreadth()
   * @generated
   */
  void setBreadth(int value);

  /**
   * Returns the value of the '<em><b>Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Height</em>' attribute.
   * @see #setHeight(int)
   * @see org.xtext.fp.FpPackage#getfindtempBuilAction_Height()
   * @model
   * @generated
   */
  int getHeight();

  /**
   * Sets the value of the '{@link org.xtext.fp.findtempBuilAction#getHeight <em>Height</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Height</em>' attribute.
   * @see #getHeight()
   * @generated
   */
  void setHeight(int value);

} // findtempBuilAction
