/**
 * generated by Xtext 2.18.0
 */
package org.xtext.fp;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.fp.FpFactory
 * @model kind="package"
 * @generated
 */
public interface FpPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "fp";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/Fp";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "fp";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  FpPackage eINSTANCE = org.xtext.fp.impl.FpPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.fp.impl.DomainModelImpl <em>Domain Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.fp.impl.DomainModelImpl
   * @see org.xtext.fp.impl.FpPackageImpl#getDomainModel()
   * @generated
   */
  int DOMAIN_MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN_MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Domain Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN_MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.fp.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.fp.impl.ModelImpl
   * @see org.xtext.fp.impl.FpPackageImpl#getModel()
   * @generated
   */
  int MODEL = 1;

  /**
   * The feature id for the '<em><b>Query</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__QUERY = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.fp.impl.QueryImpl <em>Query</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.fp.impl.QueryImpl
   * @see org.xtext.fp.impl.FpPackageImpl#getQuery()
   * @generated
   */
  int QUERY = 2;

  /**
   * The feature id for the '<em><b>Region</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY__REGION = 0;

  /**
   * The number of structural features of the '<em>Query</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.fp.impl.showRegionImpl <em>show Region</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.fp.impl.showRegionImpl
   * @see org.xtext.fp.impl.FpPackageImpl#getshowRegion()
   * @generated
   */
  int SHOW_REGION = 3;

  /**
   * The feature id for the '<em><b>Region</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHOW_REGION__REGION = QUERY__REGION;

  /**
   * The number of structural features of the '<em>show Region</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHOW_REGION_FEATURE_COUNT = QUERY_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.fp.impl.findtempBuilActionImpl <em>findtemp Buil Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.fp.impl.findtempBuilActionImpl
   * @see org.xtext.fp.impl.FpPackageImpl#getfindtempBuilAction()
   * @generated
   */
  int FINDTEMP_BUIL_ACTION = 4;

  /**
   * The feature id for the '<em><b>Region</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINDTEMP_BUIL_ACTION__REGION = QUERY__REGION;

  /**
   * The feature id for the '<em><b>No of buildings</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINDTEMP_BUIL_ACTION__NO_OF_BUILDINGS = QUERY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINDTEMP_BUIL_ACTION__LENGTH = QUERY_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Breadth</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINDTEMP_BUIL_ACTION__BREADTH = QUERY_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINDTEMP_BUIL_ACTION__HEIGHT = QUERY_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>findtemp Buil Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINDTEMP_BUIL_ACTION_FEATURE_COUNT = QUERY_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.fp.impl.caltreesBuildActionImpl <em>caltrees Build Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.fp.impl.caltreesBuildActionImpl
   * @see org.xtext.fp.impl.FpPackageImpl#getcaltreesBuildAction()
   * @generated
   */
  int CALTREES_BUILD_ACTION = 5;

  /**
   * The feature id for the '<em><b>Region</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALTREES_BUILD_ACTION__REGION = QUERY__REGION;

  /**
   * The feature id for the '<em><b>No of buildings</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALTREES_BUILD_ACTION__NO_OF_BUILDINGS = QUERY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALTREES_BUILD_ACTION__LENGTH = QUERY_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Breadth</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALTREES_BUILD_ACTION__BREADTH = QUERY_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALTREES_BUILD_ACTION__HEIGHT = QUERY_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>caltrees Build Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALTREES_BUILD_ACTION_FEATURE_COUNT = QUERY_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.fp.impl.DesignResidentialImpl <em>Design Residential</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.fp.impl.DesignResidentialImpl
   * @see org.xtext.fp.impl.FpPackageImpl#getDesignResidential()
   * @generated
   */
  int DESIGN_RESIDENTIAL = 6;

  /**
   * The feature id for the '<em><b>Region</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESIGN_RESIDENTIAL__REGION = QUERY__REGION;

  /**
   * The feature id for the '<em><b>No of people</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESIGN_RESIDENTIAL__NO_OF_PEOPLE = QUERY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Design Residential</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESIGN_RESIDENTIAL_FEATURE_COUNT = QUERY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.fp.impl.findtempDemolishImpl <em>findtemp Demolish</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.fp.impl.findtempDemolishImpl
   * @see org.xtext.fp.impl.FpPackageImpl#getfindtempDemolish()
   * @generated
   */
  int FINDTEMP_DEMOLISH = 7;

  /**
   * The feature id for the '<em><b>Region</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINDTEMP_DEMOLISH__REGION = QUERY__REGION;

  /**
   * The feature id for the '<em><b>No of buildings</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINDTEMP_DEMOLISH__NO_OF_BUILDINGS = QUERY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINDTEMP_DEMOLISH__LENGTH = QUERY_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Breadth</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINDTEMP_DEMOLISH__BREADTH = QUERY_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINDTEMP_DEMOLISH__HEIGHT = QUERY_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>findtemp Demolish</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINDTEMP_DEMOLISH_FEATURE_COUNT = QUERY_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.fp.impl.findtempPlantTreesImpl <em>findtemp Plant Trees</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.fp.impl.findtempPlantTreesImpl
   * @see org.xtext.fp.impl.FpPackageImpl#getfindtempPlantTrees()
   * @generated
   */
  int FINDTEMP_PLANT_TREES = 8;

  /**
   * The feature id for the '<em><b>Region</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINDTEMP_PLANT_TREES__REGION = QUERY__REGION;

  /**
   * The feature id for the '<em><b>No of trees</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINDTEMP_PLANT_TREES__NO_OF_TREES = QUERY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>findtemp Plant Trees</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINDTEMP_PLANT_TREES_FEATURE_COUNT = QUERY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.fp.impl.findtempCutTreesImpl <em>findtemp Cut Trees</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.fp.impl.findtempCutTreesImpl
   * @see org.xtext.fp.impl.FpPackageImpl#getfindtempCutTrees()
   * @generated
   */
  int FINDTEMP_CUT_TREES = 9;

  /**
   * The feature id for the '<em><b>Region</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINDTEMP_CUT_TREES__REGION = QUERY__REGION;

  /**
   * The feature id for the '<em><b>No of trees</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINDTEMP_CUT_TREES__NO_OF_TREES = QUERY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>findtemp Cut Trees</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINDTEMP_CUT_TREES_FEATURE_COUNT = QUERY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.fp.impl.findtempPlantBushesImpl <em>findtemp Plant Bushes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.fp.impl.findtempPlantBushesImpl
   * @see org.xtext.fp.impl.FpPackageImpl#getfindtempPlantBushes()
   * @generated
   */
  int FINDTEMP_PLANT_BUSHES = 10;

  /**
   * The feature id for the '<em><b>Region</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINDTEMP_PLANT_BUSHES__REGION = QUERY__REGION;

  /**
   * The feature id for the '<em><b>Area</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINDTEMP_PLANT_BUSHES__AREA = QUERY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>findtemp Plant Bushes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINDTEMP_PLANT_BUSHES_FEATURE_COUNT = QUERY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.fp.impl.findtempRemoveBushesImpl <em>findtemp Remove Bushes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.fp.impl.findtempRemoveBushesImpl
   * @see org.xtext.fp.impl.FpPackageImpl#getfindtempRemoveBushes()
   * @generated
   */
  int FINDTEMP_REMOVE_BUSHES = 11;

  /**
   * The feature id for the '<em><b>Region</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINDTEMP_REMOVE_BUSHES__REGION = QUERY__REGION;

  /**
   * The feature id for the '<em><b>Area</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINDTEMP_REMOVE_BUSHES__AREA = QUERY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>findtemp Remove Bushes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINDTEMP_REMOVE_BUSHES_FEATURE_COUNT = QUERY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.fp.impl.findtempCreateLakeImpl <em>findtemp Create Lake</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.fp.impl.findtempCreateLakeImpl
   * @see org.xtext.fp.impl.FpPackageImpl#getfindtempCreateLake()
   * @generated
   */
  int FINDTEMP_CREATE_LAKE = 12;

  /**
   * The feature id for the '<em><b>Region</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINDTEMP_CREATE_LAKE__REGION = QUERY__REGION;

  /**
   * The feature id for the '<em><b>Area</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINDTEMP_CREATE_LAKE__AREA = QUERY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>findtemp Create Lake</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINDTEMP_CREATE_LAKE_FEATURE_COUNT = QUERY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.fp.impl.findtempRemoveLakeImpl <em>findtemp Remove Lake</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.fp.impl.findtempRemoveLakeImpl
   * @see org.xtext.fp.impl.FpPackageImpl#getfindtempRemoveLake()
   * @generated
   */
  int FINDTEMP_REMOVE_LAKE = 13;

  /**
   * The feature id for the '<em><b>Region</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINDTEMP_REMOVE_LAKE__REGION = QUERY__REGION;

  /**
   * The feature id for the '<em><b>Area</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINDTEMP_REMOVE_LAKE__AREA = QUERY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>findtemp Remove Lake</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINDTEMP_REMOVE_LAKE_FEATURE_COUNT = QUERY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.fp.impl.DesignCommercialImpl <em>Design Commercial</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.fp.impl.DesignCommercialImpl
   * @see org.xtext.fp.impl.FpPackageImpl#getDesignCommercial()
   * @generated
   */
  int DESIGN_COMMERCIAL = 14;

  /**
   * The feature id for the '<em><b>Region</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESIGN_COMMERCIAL__REGION = QUERY__REGION;

  /**
   * The feature id for the '<em><b>No of people</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESIGN_COMMERCIAL__NO_OF_PEOPLE = QUERY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Design Commercial</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESIGN_COMMERCIAL_FEATURE_COUNT = QUERY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.fp.impl.DesignEducationalImpl <em>Design Educational</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.fp.impl.DesignEducationalImpl
   * @see org.xtext.fp.impl.FpPackageImpl#getDesignEducational()
   * @generated
   */
  int DESIGN_EDUCATIONAL = 15;

  /**
   * The feature id for the '<em><b>Region</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESIGN_EDUCATIONAL__REGION = QUERY__REGION;

  /**
   * The feature id for the '<em><b>No of people</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESIGN_EDUCATIONAL__NO_OF_PEOPLE = QUERY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Design Educational</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESIGN_EDUCATIONAL_FEATURE_COUNT = QUERY_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.fp.DomainModel <em>Domain Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Domain Model</em>'.
   * @see org.xtext.fp.DomainModel
   * @generated
   */
  EClass getDomainModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.fp.DomainModel#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.fp.DomainModel#getElements()
   * @see #getDomainModel()
   * @generated
   */
  EReference getDomainModel_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.fp.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.fp.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.fp.Model#getQuery <em>Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Query</em>'.
   * @see org.xtext.fp.Model#getQuery()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Query();

  /**
   * Returns the meta object for class '{@link org.xtext.fp.Query <em>Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Query</em>'.
   * @see org.xtext.fp.Query
   * @generated
   */
  EClass getQuery();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.fp.Query#getRegion <em>Region</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Region</em>'.
   * @see org.xtext.fp.Query#getRegion()
   * @see #getQuery()
   * @generated
   */
  EAttribute getQuery_Region();

  /**
   * Returns the meta object for class '{@link org.xtext.fp.showRegion <em>show Region</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>show Region</em>'.
   * @see org.xtext.fp.showRegion
   * @generated
   */
  EClass getshowRegion();

  /**
   * Returns the meta object for class '{@link org.xtext.fp.findtempBuilAction <em>findtemp Buil Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>findtemp Buil Action</em>'.
   * @see org.xtext.fp.findtempBuilAction
   * @generated
   */
  EClass getfindtempBuilAction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.fp.findtempBuilAction#getNo_of_buildings <em>No of buildings</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>No of buildings</em>'.
   * @see org.xtext.fp.findtempBuilAction#getNo_of_buildings()
   * @see #getfindtempBuilAction()
   * @generated
   */
  EAttribute getfindtempBuilAction_No_of_buildings();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.fp.findtempBuilAction#getLength <em>Length</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Length</em>'.
   * @see org.xtext.fp.findtempBuilAction#getLength()
   * @see #getfindtempBuilAction()
   * @generated
   */
  EAttribute getfindtempBuilAction_Length();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.fp.findtempBuilAction#getBreadth <em>Breadth</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Breadth</em>'.
   * @see org.xtext.fp.findtempBuilAction#getBreadth()
   * @see #getfindtempBuilAction()
   * @generated
   */
  EAttribute getfindtempBuilAction_Breadth();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.fp.findtempBuilAction#getHeight <em>Height</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Height</em>'.
   * @see org.xtext.fp.findtempBuilAction#getHeight()
   * @see #getfindtempBuilAction()
   * @generated
   */
  EAttribute getfindtempBuilAction_Height();

  /**
   * Returns the meta object for class '{@link org.xtext.fp.caltreesBuildAction <em>caltrees Build Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>caltrees Build Action</em>'.
   * @see org.xtext.fp.caltreesBuildAction
   * @generated
   */
  EClass getcaltreesBuildAction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.fp.caltreesBuildAction#getNo_of_buildings <em>No of buildings</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>No of buildings</em>'.
   * @see org.xtext.fp.caltreesBuildAction#getNo_of_buildings()
   * @see #getcaltreesBuildAction()
   * @generated
   */
  EAttribute getcaltreesBuildAction_No_of_buildings();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.fp.caltreesBuildAction#getLength <em>Length</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Length</em>'.
   * @see org.xtext.fp.caltreesBuildAction#getLength()
   * @see #getcaltreesBuildAction()
   * @generated
   */
  EAttribute getcaltreesBuildAction_Length();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.fp.caltreesBuildAction#getBreadth <em>Breadth</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Breadth</em>'.
   * @see org.xtext.fp.caltreesBuildAction#getBreadth()
   * @see #getcaltreesBuildAction()
   * @generated
   */
  EAttribute getcaltreesBuildAction_Breadth();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.fp.caltreesBuildAction#getHeight <em>Height</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Height</em>'.
   * @see org.xtext.fp.caltreesBuildAction#getHeight()
   * @see #getcaltreesBuildAction()
   * @generated
   */
  EAttribute getcaltreesBuildAction_Height();

  /**
   * Returns the meta object for class '{@link org.xtext.fp.DesignResidential <em>Design Residential</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Design Residential</em>'.
   * @see org.xtext.fp.DesignResidential
   * @generated
   */
  EClass getDesignResidential();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.fp.DesignResidential#getNo_of_people <em>No of people</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>No of people</em>'.
   * @see org.xtext.fp.DesignResidential#getNo_of_people()
   * @see #getDesignResidential()
   * @generated
   */
  EAttribute getDesignResidential_No_of_people();

  /**
   * Returns the meta object for class '{@link org.xtext.fp.findtempDemolish <em>findtemp Demolish</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>findtemp Demolish</em>'.
   * @see org.xtext.fp.findtempDemolish
   * @generated
   */
  EClass getfindtempDemolish();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.fp.findtempDemolish#getNo_of_buildings <em>No of buildings</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>No of buildings</em>'.
   * @see org.xtext.fp.findtempDemolish#getNo_of_buildings()
   * @see #getfindtempDemolish()
   * @generated
   */
  EAttribute getfindtempDemolish_No_of_buildings();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.fp.findtempDemolish#getLength <em>Length</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Length</em>'.
   * @see org.xtext.fp.findtempDemolish#getLength()
   * @see #getfindtempDemolish()
   * @generated
   */
  EAttribute getfindtempDemolish_Length();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.fp.findtempDemolish#getBreadth <em>Breadth</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Breadth</em>'.
   * @see org.xtext.fp.findtempDemolish#getBreadth()
   * @see #getfindtempDemolish()
   * @generated
   */
  EAttribute getfindtempDemolish_Breadth();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.fp.findtempDemolish#getHeight <em>Height</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Height</em>'.
   * @see org.xtext.fp.findtempDemolish#getHeight()
   * @see #getfindtempDemolish()
   * @generated
   */
  EAttribute getfindtempDemolish_Height();

  /**
   * Returns the meta object for class '{@link org.xtext.fp.findtempPlantTrees <em>findtemp Plant Trees</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>findtemp Plant Trees</em>'.
   * @see org.xtext.fp.findtempPlantTrees
   * @generated
   */
  EClass getfindtempPlantTrees();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.fp.findtempPlantTrees#getNo_of_trees <em>No of trees</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>No of trees</em>'.
   * @see org.xtext.fp.findtempPlantTrees#getNo_of_trees()
   * @see #getfindtempPlantTrees()
   * @generated
   */
  EAttribute getfindtempPlantTrees_No_of_trees();

  /**
   * Returns the meta object for class '{@link org.xtext.fp.findtempCutTrees <em>findtemp Cut Trees</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>findtemp Cut Trees</em>'.
   * @see org.xtext.fp.findtempCutTrees
   * @generated
   */
  EClass getfindtempCutTrees();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.fp.findtempCutTrees#getNo_of_trees <em>No of trees</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>No of trees</em>'.
   * @see org.xtext.fp.findtempCutTrees#getNo_of_trees()
   * @see #getfindtempCutTrees()
   * @generated
   */
  EAttribute getfindtempCutTrees_No_of_trees();

  /**
   * Returns the meta object for class '{@link org.xtext.fp.findtempPlantBushes <em>findtemp Plant Bushes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>findtemp Plant Bushes</em>'.
   * @see org.xtext.fp.findtempPlantBushes
   * @generated
   */
  EClass getfindtempPlantBushes();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.fp.findtempPlantBushes#getArea <em>Area</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Area</em>'.
   * @see org.xtext.fp.findtempPlantBushes#getArea()
   * @see #getfindtempPlantBushes()
   * @generated
   */
  EAttribute getfindtempPlantBushes_Area();

  /**
   * Returns the meta object for class '{@link org.xtext.fp.findtempRemoveBushes <em>findtemp Remove Bushes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>findtemp Remove Bushes</em>'.
   * @see org.xtext.fp.findtempRemoveBushes
   * @generated
   */
  EClass getfindtempRemoveBushes();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.fp.findtempRemoveBushes#getArea <em>Area</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Area</em>'.
   * @see org.xtext.fp.findtempRemoveBushes#getArea()
   * @see #getfindtempRemoveBushes()
   * @generated
   */
  EAttribute getfindtempRemoveBushes_Area();

  /**
   * Returns the meta object for class '{@link org.xtext.fp.findtempCreateLake <em>findtemp Create Lake</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>findtemp Create Lake</em>'.
   * @see org.xtext.fp.findtempCreateLake
   * @generated
   */
  EClass getfindtempCreateLake();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.fp.findtempCreateLake#getArea <em>Area</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Area</em>'.
   * @see org.xtext.fp.findtempCreateLake#getArea()
   * @see #getfindtempCreateLake()
   * @generated
   */
  EAttribute getfindtempCreateLake_Area();

  /**
   * Returns the meta object for class '{@link org.xtext.fp.findtempRemoveLake <em>findtemp Remove Lake</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>findtemp Remove Lake</em>'.
   * @see org.xtext.fp.findtempRemoveLake
   * @generated
   */
  EClass getfindtempRemoveLake();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.fp.findtempRemoveLake#getArea <em>Area</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Area</em>'.
   * @see org.xtext.fp.findtempRemoveLake#getArea()
   * @see #getfindtempRemoveLake()
   * @generated
   */
  EAttribute getfindtempRemoveLake_Area();

  /**
   * Returns the meta object for class '{@link org.xtext.fp.DesignCommercial <em>Design Commercial</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Design Commercial</em>'.
   * @see org.xtext.fp.DesignCommercial
   * @generated
   */
  EClass getDesignCommercial();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.fp.DesignCommercial#getNo_of_people <em>No of people</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>No of people</em>'.
   * @see org.xtext.fp.DesignCommercial#getNo_of_people()
   * @see #getDesignCommercial()
   * @generated
   */
  EAttribute getDesignCommercial_No_of_people();

  /**
   * Returns the meta object for class '{@link org.xtext.fp.DesignEducational <em>Design Educational</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Design Educational</em>'.
   * @see org.xtext.fp.DesignEducational
   * @generated
   */
  EClass getDesignEducational();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.fp.DesignEducational#getNo_of_people <em>No of people</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>No of people</em>'.
   * @see org.xtext.fp.DesignEducational#getNo_of_people()
   * @see #getDesignEducational()
   * @generated
   */
  EAttribute getDesignEducational_No_of_people();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  FpFactory getFpFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.fp.impl.DomainModelImpl <em>Domain Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.fp.impl.DomainModelImpl
     * @see org.xtext.fp.impl.FpPackageImpl#getDomainModel()
     * @generated
     */
    EClass DOMAIN_MODEL = eINSTANCE.getDomainModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOMAIN_MODEL__ELEMENTS = eINSTANCE.getDomainModel_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.fp.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.fp.impl.ModelImpl
     * @see org.xtext.fp.impl.FpPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Query</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__QUERY = eINSTANCE.getModel_Query();

    /**
     * The meta object literal for the '{@link org.xtext.fp.impl.QueryImpl <em>Query</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.fp.impl.QueryImpl
     * @see org.xtext.fp.impl.FpPackageImpl#getQuery()
     * @generated
     */
    EClass QUERY = eINSTANCE.getQuery();

    /**
     * The meta object literal for the '<em><b>Region</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QUERY__REGION = eINSTANCE.getQuery_Region();

    /**
     * The meta object literal for the '{@link org.xtext.fp.impl.showRegionImpl <em>show Region</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.fp.impl.showRegionImpl
     * @see org.xtext.fp.impl.FpPackageImpl#getshowRegion()
     * @generated
     */
    EClass SHOW_REGION = eINSTANCE.getshowRegion();

    /**
     * The meta object literal for the '{@link org.xtext.fp.impl.findtempBuilActionImpl <em>findtemp Buil Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.fp.impl.findtempBuilActionImpl
     * @see org.xtext.fp.impl.FpPackageImpl#getfindtempBuilAction()
     * @generated
     */
    EClass FINDTEMP_BUIL_ACTION = eINSTANCE.getfindtempBuilAction();

    /**
     * The meta object literal for the '<em><b>No of buildings</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FINDTEMP_BUIL_ACTION__NO_OF_BUILDINGS = eINSTANCE.getfindtempBuilAction_No_of_buildings();

    /**
     * The meta object literal for the '<em><b>Length</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FINDTEMP_BUIL_ACTION__LENGTH = eINSTANCE.getfindtempBuilAction_Length();

    /**
     * The meta object literal for the '<em><b>Breadth</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FINDTEMP_BUIL_ACTION__BREADTH = eINSTANCE.getfindtempBuilAction_Breadth();

    /**
     * The meta object literal for the '<em><b>Height</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FINDTEMP_BUIL_ACTION__HEIGHT = eINSTANCE.getfindtempBuilAction_Height();

    /**
     * The meta object literal for the '{@link org.xtext.fp.impl.caltreesBuildActionImpl <em>caltrees Build Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.fp.impl.caltreesBuildActionImpl
     * @see org.xtext.fp.impl.FpPackageImpl#getcaltreesBuildAction()
     * @generated
     */
    EClass CALTREES_BUILD_ACTION = eINSTANCE.getcaltreesBuildAction();

    /**
     * The meta object literal for the '<em><b>No of buildings</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALTREES_BUILD_ACTION__NO_OF_BUILDINGS = eINSTANCE.getcaltreesBuildAction_No_of_buildings();

    /**
     * The meta object literal for the '<em><b>Length</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALTREES_BUILD_ACTION__LENGTH = eINSTANCE.getcaltreesBuildAction_Length();

    /**
     * The meta object literal for the '<em><b>Breadth</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALTREES_BUILD_ACTION__BREADTH = eINSTANCE.getcaltreesBuildAction_Breadth();

    /**
     * The meta object literal for the '<em><b>Height</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALTREES_BUILD_ACTION__HEIGHT = eINSTANCE.getcaltreesBuildAction_Height();

    /**
     * The meta object literal for the '{@link org.xtext.fp.impl.DesignResidentialImpl <em>Design Residential</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.fp.impl.DesignResidentialImpl
     * @see org.xtext.fp.impl.FpPackageImpl#getDesignResidential()
     * @generated
     */
    EClass DESIGN_RESIDENTIAL = eINSTANCE.getDesignResidential();

    /**
     * The meta object literal for the '<em><b>No of people</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DESIGN_RESIDENTIAL__NO_OF_PEOPLE = eINSTANCE.getDesignResidential_No_of_people();

    /**
     * The meta object literal for the '{@link org.xtext.fp.impl.findtempDemolishImpl <em>findtemp Demolish</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.fp.impl.findtempDemolishImpl
     * @see org.xtext.fp.impl.FpPackageImpl#getfindtempDemolish()
     * @generated
     */
    EClass FINDTEMP_DEMOLISH = eINSTANCE.getfindtempDemolish();

    /**
     * The meta object literal for the '<em><b>No of buildings</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FINDTEMP_DEMOLISH__NO_OF_BUILDINGS = eINSTANCE.getfindtempDemolish_No_of_buildings();

    /**
     * The meta object literal for the '<em><b>Length</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FINDTEMP_DEMOLISH__LENGTH = eINSTANCE.getfindtempDemolish_Length();

    /**
     * The meta object literal for the '<em><b>Breadth</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FINDTEMP_DEMOLISH__BREADTH = eINSTANCE.getfindtempDemolish_Breadth();

    /**
     * The meta object literal for the '<em><b>Height</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FINDTEMP_DEMOLISH__HEIGHT = eINSTANCE.getfindtempDemolish_Height();

    /**
     * The meta object literal for the '{@link org.xtext.fp.impl.findtempPlantTreesImpl <em>findtemp Plant Trees</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.fp.impl.findtempPlantTreesImpl
     * @see org.xtext.fp.impl.FpPackageImpl#getfindtempPlantTrees()
     * @generated
     */
    EClass FINDTEMP_PLANT_TREES = eINSTANCE.getfindtempPlantTrees();

    /**
     * The meta object literal for the '<em><b>No of trees</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FINDTEMP_PLANT_TREES__NO_OF_TREES = eINSTANCE.getfindtempPlantTrees_No_of_trees();

    /**
     * The meta object literal for the '{@link org.xtext.fp.impl.findtempCutTreesImpl <em>findtemp Cut Trees</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.fp.impl.findtempCutTreesImpl
     * @see org.xtext.fp.impl.FpPackageImpl#getfindtempCutTrees()
     * @generated
     */
    EClass FINDTEMP_CUT_TREES = eINSTANCE.getfindtempCutTrees();

    /**
     * The meta object literal for the '<em><b>No of trees</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FINDTEMP_CUT_TREES__NO_OF_TREES = eINSTANCE.getfindtempCutTrees_No_of_trees();

    /**
     * The meta object literal for the '{@link org.xtext.fp.impl.findtempPlantBushesImpl <em>findtemp Plant Bushes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.fp.impl.findtempPlantBushesImpl
     * @see org.xtext.fp.impl.FpPackageImpl#getfindtempPlantBushes()
     * @generated
     */
    EClass FINDTEMP_PLANT_BUSHES = eINSTANCE.getfindtempPlantBushes();

    /**
     * The meta object literal for the '<em><b>Area</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FINDTEMP_PLANT_BUSHES__AREA = eINSTANCE.getfindtempPlantBushes_Area();

    /**
     * The meta object literal for the '{@link org.xtext.fp.impl.findtempRemoveBushesImpl <em>findtemp Remove Bushes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.fp.impl.findtempRemoveBushesImpl
     * @see org.xtext.fp.impl.FpPackageImpl#getfindtempRemoveBushes()
     * @generated
     */
    EClass FINDTEMP_REMOVE_BUSHES = eINSTANCE.getfindtempRemoveBushes();

    /**
     * The meta object literal for the '<em><b>Area</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FINDTEMP_REMOVE_BUSHES__AREA = eINSTANCE.getfindtempRemoveBushes_Area();

    /**
     * The meta object literal for the '{@link org.xtext.fp.impl.findtempCreateLakeImpl <em>findtemp Create Lake</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.fp.impl.findtempCreateLakeImpl
     * @see org.xtext.fp.impl.FpPackageImpl#getfindtempCreateLake()
     * @generated
     */
    EClass FINDTEMP_CREATE_LAKE = eINSTANCE.getfindtempCreateLake();

    /**
     * The meta object literal for the '<em><b>Area</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FINDTEMP_CREATE_LAKE__AREA = eINSTANCE.getfindtempCreateLake_Area();

    /**
     * The meta object literal for the '{@link org.xtext.fp.impl.findtempRemoveLakeImpl <em>findtemp Remove Lake</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.fp.impl.findtempRemoveLakeImpl
     * @see org.xtext.fp.impl.FpPackageImpl#getfindtempRemoveLake()
     * @generated
     */
    EClass FINDTEMP_REMOVE_LAKE = eINSTANCE.getfindtempRemoveLake();

    /**
     * The meta object literal for the '<em><b>Area</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FINDTEMP_REMOVE_LAKE__AREA = eINSTANCE.getfindtempRemoveLake_Area();

    /**
     * The meta object literal for the '{@link org.xtext.fp.impl.DesignCommercialImpl <em>Design Commercial</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.fp.impl.DesignCommercialImpl
     * @see org.xtext.fp.impl.FpPackageImpl#getDesignCommercial()
     * @generated
     */
    EClass DESIGN_COMMERCIAL = eINSTANCE.getDesignCommercial();

    /**
     * The meta object literal for the '<em><b>No of people</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DESIGN_COMMERCIAL__NO_OF_PEOPLE = eINSTANCE.getDesignCommercial_No_of_people();

    /**
     * The meta object literal for the '{@link org.xtext.fp.impl.DesignEducationalImpl <em>Design Educational</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.fp.impl.DesignEducationalImpl
     * @see org.xtext.fp.impl.FpPackageImpl#getDesignEducational()
     * @generated
     */
    EClass DESIGN_EDUCATIONAL = eINSTANCE.getDesignEducational();

    /**
     * The meta object literal for the '<em><b>No of people</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DESIGN_EDUCATIONAL__NO_OF_PEOPLE = eINSTANCE.getDesignEducational_No_of_people();

  }

} //FpPackage
