/**
 * generated by Xtext 2.18.0
 */
package org.xtext.fp;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.fp.Model#getQuery <em>Query</em>}</li>
 * </ul>
 *
 * @see org.xtext.fp.FpPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Query</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.fp.Query}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Query</em>' containment reference list.
   * @see org.xtext.fp.FpPackage#getModel_Query()
   * @model containment="true"
   * @generated
   */
  EList<Query> getQuery();

} // Model
