/**
 * generated by Xtext 2.18.0
 */
package org.xtext.fp;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Query</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.fp.Query#getRegion <em>Region</em>}</li>
 * </ul>
 *
 * @see org.xtext.fp.FpPackage#getQuery()
 * @model
 * @generated
 */
public interface Query extends EObject
{
  /**
   * Returns the value of the '<em><b>Region</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Region</em>' attribute.
   * @see #setRegion(int)
   * @see org.xtext.fp.FpPackage#getQuery_Region()
   * @model
   * @generated
   */
  int getRegion();

  /**
   * Sets the value of the '{@link org.xtext.fp.Query#getRegion <em>Region</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Region</em>' attribute.
   * @see #getRegion()
   * @generated
   */
  void setRegion(int value);

} // Query
