/**
 * generated by Xtext 2.18.0
 */
package org.xtext.fp;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>show Region</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.fp.FpPackage#getshowRegion()
 * @model
 * @generated
 */
public interface showRegion extends Query
{
} // showRegion
