/*
 * generated by Xtext 2.18.0
 */
package org.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MycnlStandaloneSetup extends MycnlStandaloneSetupGenerated {

	def static void doSetup() {
		new MycnlStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
