/**
 * generated by Xtext 2.18.0
 */
package org.xtext.fp.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.fp.DesignCommercial;
import org.xtext.fp.FpPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Design Commercial</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.fp.impl.DesignCommercialImpl#getNo_of_people <em>No of people</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DesignCommercialImpl extends QueryImpl implements DesignCommercial
{
  /**
   * The default value of the '{@link #getNo_of_people() <em>No of people</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNo_of_people()
   * @generated
   * @ordered
   */
  protected static final int NO_OF_PEOPLE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getNo_of_people() <em>No of people</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNo_of_people()
   * @generated
   * @ordered
   */
  protected int no_of_people = NO_OF_PEOPLE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DesignCommercialImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FpPackage.Literals.DESIGN_COMMERCIAL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getNo_of_people()
  {
    return no_of_people;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNo_of_people(int newNo_of_people)
  {
    int oldNo_of_people = no_of_people;
    no_of_people = newNo_of_people;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FpPackage.DESIGN_COMMERCIAL__NO_OF_PEOPLE, oldNo_of_people, no_of_people));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FpPackage.DESIGN_COMMERCIAL__NO_OF_PEOPLE:
        return getNo_of_people();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FpPackage.DESIGN_COMMERCIAL__NO_OF_PEOPLE:
        setNo_of_people((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FpPackage.DESIGN_COMMERCIAL__NO_OF_PEOPLE:
        setNo_of_people(NO_OF_PEOPLE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FpPackage.DESIGN_COMMERCIAL__NO_OF_PEOPLE:
        return no_of_people != NO_OF_PEOPLE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (no_of_people: ");
    result.append(no_of_people);
    result.append(')');
    return result.toString();
  }

} //DesignCommercialImpl
