/**
 * generated by Xtext 2.18.0
 */
package org.xtext.fp.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.fp.FpPackage;
import org.xtext.fp.findtempCutTrees;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>findtemp Cut Trees</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.fp.impl.findtempCutTreesImpl#getNo_of_trees <em>No of trees</em>}</li>
 * </ul>
 *
 * @generated
 */
public class findtempCutTreesImpl extends QueryImpl implements findtempCutTrees
{
  /**
   * The default value of the '{@link #getNo_of_trees() <em>No of trees</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNo_of_trees()
   * @generated
   * @ordered
   */
  protected static final int NO_OF_TREES_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getNo_of_trees() <em>No of trees</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNo_of_trees()
   * @generated
   * @ordered
   */
  protected int no_of_trees = NO_OF_TREES_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected findtempCutTreesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FpPackage.Literals.FINDTEMP_CUT_TREES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getNo_of_trees()
  {
    return no_of_trees;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNo_of_trees(int newNo_of_trees)
  {
    int oldNo_of_trees = no_of_trees;
    no_of_trees = newNo_of_trees;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FpPackage.FINDTEMP_CUT_TREES__NO_OF_TREES, oldNo_of_trees, no_of_trees));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FpPackage.FINDTEMP_CUT_TREES__NO_OF_TREES:
        return getNo_of_trees();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FpPackage.FINDTEMP_CUT_TREES__NO_OF_TREES:
        setNo_of_trees((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FpPackage.FINDTEMP_CUT_TREES__NO_OF_TREES:
        setNo_of_trees(NO_OF_TREES_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FpPackage.FINDTEMP_CUT_TREES__NO_OF_TREES:
        return no_of_trees != NO_OF_TREES_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (no_of_trees: ");
    result.append(no_of_trees);
    result.append(')');
    return result.toString();
  }

} //findtempCutTreesImpl
