/**
 * generated by Xtext 2.18.0
 */
package org.xtext.fp.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.fp.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class FpFactoryImpl extends EFactoryImpl implements FpFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static FpFactory init()
  {
    try
    {
      FpFactory theFpFactory = (FpFactory)EPackage.Registry.INSTANCE.getEFactory(FpPackage.eNS_URI);
      if (theFpFactory != null)
      {
        return theFpFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new FpFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FpFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case FpPackage.DOMAIN_MODEL: return createDomainModel();
      case FpPackage.MODEL: return createModel();
      case FpPackage.QUERY: return createQuery();
      case FpPackage.SHOW_REGION: return createshowRegion();
      case FpPackage.FINDTEMP_BUIL_ACTION: return createfindtempBuilAction();
      case FpPackage.CALTREES_BUILD_ACTION: return createcaltreesBuildAction();
      case FpPackage.DESIGN_RESIDENTIAL: return createDesignResidential();
      case FpPackage.FINDTEMP_DEMOLISH: return createfindtempDemolish();
      case FpPackage.FINDTEMP_PLANT_TREES: return createfindtempPlantTrees();
      case FpPackage.FINDTEMP_CUT_TREES: return createfindtempCutTrees();
      case FpPackage.FINDTEMP_PLANT_BUSHES: return createfindtempPlantBushes();
      case FpPackage.FINDTEMP_REMOVE_BUSHES: return createfindtempRemoveBushes();
      case FpPackage.FINDTEMP_CREATE_LAKE: return createfindtempCreateLake();
      case FpPackage.FINDTEMP_REMOVE_LAKE: return createfindtempRemoveLake();
      case FpPackage.DESIGN_COMMERCIAL: return createDesignCommercial();
      case FpPackage.DESIGN_EDUCATIONAL: return createDesignEducational();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DomainModel createDomainModel()
  {
    DomainModelImpl domainModel = new DomainModelImpl();
    return domainModel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Query createQuery()
  {
    QueryImpl query = new QueryImpl();
    return query;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public showRegion createshowRegion()
  {
    showRegionImpl showRegion = new showRegionImpl();
    return showRegion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public findtempBuilAction createfindtempBuilAction()
  {
    findtempBuilActionImpl findtempBuilAction = new findtempBuilActionImpl();
    return findtempBuilAction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public caltreesBuildAction createcaltreesBuildAction()
  {
    caltreesBuildActionImpl caltreesBuildAction = new caltreesBuildActionImpl();
    return caltreesBuildAction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DesignResidential createDesignResidential()
  {
    DesignResidentialImpl designResidential = new DesignResidentialImpl();
    return designResidential;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public findtempDemolish createfindtempDemolish()
  {
    findtempDemolishImpl findtempDemolish = new findtempDemolishImpl();
    return findtempDemolish;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public findtempPlantTrees createfindtempPlantTrees()
  {
    findtempPlantTreesImpl findtempPlantTrees = new findtempPlantTreesImpl();
    return findtempPlantTrees;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public findtempCutTrees createfindtempCutTrees()
  {
    findtempCutTreesImpl findtempCutTrees = new findtempCutTreesImpl();
    return findtempCutTrees;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public findtempPlantBushes createfindtempPlantBushes()
  {
    findtempPlantBushesImpl findtempPlantBushes = new findtempPlantBushesImpl();
    return findtempPlantBushes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public findtempRemoveBushes createfindtempRemoveBushes()
  {
    findtempRemoveBushesImpl findtempRemoveBushes = new findtempRemoveBushesImpl();
    return findtempRemoveBushes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public findtempCreateLake createfindtempCreateLake()
  {
    findtempCreateLakeImpl findtempCreateLake = new findtempCreateLakeImpl();
    return findtempCreateLake;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public findtempRemoveLake createfindtempRemoveLake()
  {
    findtempRemoveLakeImpl findtempRemoveLake = new findtempRemoveLakeImpl();
    return findtempRemoveLake;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DesignCommercial createDesignCommercial()
  {
    DesignCommercialImpl designCommercial = new DesignCommercialImpl();
    return designCommercial;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DesignEducational createDesignEducational()
  {
    DesignEducationalImpl designEducational = new DesignEducationalImpl();
    return designEducational;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FpPackage getFpPackage()
  {
    return (FpPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static FpPackage getPackage()
  {
    return FpPackage.eINSTANCE;
  }

} //FpFactoryImpl
