/**
 * generated by Xtext 2.18.0
 */
package org.xtext.fp.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.fp.DesignCommercial;
import org.xtext.fp.DesignEducational;
import org.xtext.fp.DesignResidential;
import org.xtext.fp.DomainModel;
import org.xtext.fp.FpFactory;
import org.xtext.fp.FpPackage;
import org.xtext.fp.Model;
import org.xtext.fp.Query;
import org.xtext.fp.caltreesBuildAction;
import org.xtext.fp.findtempBuilAction;
import org.xtext.fp.findtempCreateLake;
import org.xtext.fp.findtempCutTrees;
import org.xtext.fp.findtempDemolish;
import org.xtext.fp.findtempPlantBushes;
import org.xtext.fp.findtempPlantTrees;
import org.xtext.fp.findtempRemoveBushes;
import org.xtext.fp.findtempRemoveLake;
import org.xtext.fp.showRegion;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class FpPackageImpl extends EPackageImpl implements FpPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass domainModelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass queryEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass showRegionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass findtempBuilActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass caltreesBuildActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass designResidentialEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass findtempDemolishEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass findtempPlantTreesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass findtempCutTreesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass findtempPlantBushesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass findtempRemoveBushesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass findtempCreateLakeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass findtempRemoveLakeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass designCommercialEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass designEducationalEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.fp.FpPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private FpPackageImpl()
  {
    super(eNS_URI, FpFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link FpPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static FpPackage init()
  {
    if (isInited) return (FpPackage)EPackage.Registry.INSTANCE.getEPackage(FpPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredFpPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    FpPackageImpl theFpPackage = registeredFpPackage instanceof FpPackageImpl ? (FpPackageImpl)registeredFpPackage : new FpPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theFpPackage.createPackageContents();

    // Initialize created meta-data
    theFpPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theFpPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(FpPackage.eNS_URI, theFpPackage);
    return theFpPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDomainModel()
  {
    return domainModelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDomainModel_Elements()
  {
    return (EReference)domainModelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModel()
  {
    return modelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_Query()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getQuery()
  {
    return queryEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getQuery_Region()
  {
    return (EAttribute)queryEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getshowRegion()
  {
    return showRegionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getfindtempBuilAction()
  {
    return findtempBuilActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getfindtempBuilAction_No_of_buildings()
  {
    return (EAttribute)findtempBuilActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getfindtempBuilAction_Length()
  {
    return (EAttribute)findtempBuilActionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getfindtempBuilAction_Breadth()
  {
    return (EAttribute)findtempBuilActionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getfindtempBuilAction_Height()
  {
    return (EAttribute)findtempBuilActionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getcaltreesBuildAction()
  {
    return caltreesBuildActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getcaltreesBuildAction_No_of_buildings()
  {
    return (EAttribute)caltreesBuildActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getcaltreesBuildAction_Length()
  {
    return (EAttribute)caltreesBuildActionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getcaltreesBuildAction_Breadth()
  {
    return (EAttribute)caltreesBuildActionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getcaltreesBuildAction_Height()
  {
    return (EAttribute)caltreesBuildActionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDesignResidential()
  {
    return designResidentialEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDesignResidential_No_of_people()
  {
    return (EAttribute)designResidentialEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getfindtempDemolish()
  {
    return findtempDemolishEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getfindtempDemolish_No_of_buildings()
  {
    return (EAttribute)findtempDemolishEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getfindtempDemolish_Length()
  {
    return (EAttribute)findtempDemolishEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getfindtempDemolish_Breadth()
  {
    return (EAttribute)findtempDemolishEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getfindtempDemolish_Height()
  {
    return (EAttribute)findtempDemolishEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getfindtempPlantTrees()
  {
    return findtempPlantTreesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getfindtempPlantTrees_No_of_trees()
  {
    return (EAttribute)findtempPlantTreesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getfindtempCutTrees()
  {
    return findtempCutTreesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getfindtempCutTrees_No_of_trees()
  {
    return (EAttribute)findtempCutTreesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getfindtempPlantBushes()
  {
    return findtempPlantBushesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getfindtempPlantBushes_Area()
  {
    return (EAttribute)findtempPlantBushesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getfindtempRemoveBushes()
  {
    return findtempRemoveBushesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getfindtempRemoveBushes_Area()
  {
    return (EAttribute)findtempRemoveBushesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getfindtempCreateLake()
  {
    return findtempCreateLakeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getfindtempCreateLake_Area()
  {
    return (EAttribute)findtempCreateLakeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getfindtempRemoveLake()
  {
    return findtempRemoveLakeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getfindtempRemoveLake_Area()
  {
    return (EAttribute)findtempRemoveLakeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDesignCommercial()
  {
    return designCommercialEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDesignCommercial_No_of_people()
  {
    return (EAttribute)designCommercialEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDesignEducational()
  {
    return designEducationalEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDesignEducational_No_of_people()
  {
    return (EAttribute)designEducationalEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FpFactory getFpFactory()
  {
    return (FpFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    domainModelEClass = createEClass(DOMAIN_MODEL);
    createEReference(domainModelEClass, DOMAIN_MODEL__ELEMENTS);

    modelEClass = createEClass(MODEL);
    createEReference(modelEClass, MODEL__QUERY);

    queryEClass = createEClass(QUERY);
    createEAttribute(queryEClass, QUERY__REGION);

    showRegionEClass = createEClass(SHOW_REGION);

    findtempBuilActionEClass = createEClass(FINDTEMP_BUIL_ACTION);
    createEAttribute(findtempBuilActionEClass, FINDTEMP_BUIL_ACTION__NO_OF_BUILDINGS);
    createEAttribute(findtempBuilActionEClass, FINDTEMP_BUIL_ACTION__LENGTH);
    createEAttribute(findtempBuilActionEClass, FINDTEMP_BUIL_ACTION__BREADTH);
    createEAttribute(findtempBuilActionEClass, FINDTEMP_BUIL_ACTION__HEIGHT);

    caltreesBuildActionEClass = createEClass(CALTREES_BUILD_ACTION);
    createEAttribute(caltreesBuildActionEClass, CALTREES_BUILD_ACTION__NO_OF_BUILDINGS);
    createEAttribute(caltreesBuildActionEClass, CALTREES_BUILD_ACTION__LENGTH);
    createEAttribute(caltreesBuildActionEClass, CALTREES_BUILD_ACTION__BREADTH);
    createEAttribute(caltreesBuildActionEClass, CALTREES_BUILD_ACTION__HEIGHT);

    designResidentialEClass = createEClass(DESIGN_RESIDENTIAL);
    createEAttribute(designResidentialEClass, DESIGN_RESIDENTIAL__NO_OF_PEOPLE);

    findtempDemolishEClass = createEClass(FINDTEMP_DEMOLISH);
    createEAttribute(findtempDemolishEClass, FINDTEMP_DEMOLISH__NO_OF_BUILDINGS);
    createEAttribute(findtempDemolishEClass, FINDTEMP_DEMOLISH__LENGTH);
    createEAttribute(findtempDemolishEClass, FINDTEMP_DEMOLISH__BREADTH);
    createEAttribute(findtempDemolishEClass, FINDTEMP_DEMOLISH__HEIGHT);

    findtempPlantTreesEClass = createEClass(FINDTEMP_PLANT_TREES);
    createEAttribute(findtempPlantTreesEClass, FINDTEMP_PLANT_TREES__NO_OF_TREES);

    findtempCutTreesEClass = createEClass(FINDTEMP_CUT_TREES);
    createEAttribute(findtempCutTreesEClass, FINDTEMP_CUT_TREES__NO_OF_TREES);

    findtempPlantBushesEClass = createEClass(FINDTEMP_PLANT_BUSHES);
    createEAttribute(findtempPlantBushesEClass, FINDTEMP_PLANT_BUSHES__AREA);

    findtempRemoveBushesEClass = createEClass(FINDTEMP_REMOVE_BUSHES);
    createEAttribute(findtempRemoveBushesEClass, FINDTEMP_REMOVE_BUSHES__AREA);

    findtempCreateLakeEClass = createEClass(FINDTEMP_CREATE_LAKE);
    createEAttribute(findtempCreateLakeEClass, FINDTEMP_CREATE_LAKE__AREA);

    findtempRemoveLakeEClass = createEClass(FINDTEMP_REMOVE_LAKE);
    createEAttribute(findtempRemoveLakeEClass, FINDTEMP_REMOVE_LAKE__AREA);

    designCommercialEClass = createEClass(DESIGN_COMMERCIAL);
    createEAttribute(designCommercialEClass, DESIGN_COMMERCIAL__NO_OF_PEOPLE);

    designEducationalEClass = createEClass(DESIGN_EDUCATIONAL);
    createEAttribute(designEducationalEClass, DESIGN_EDUCATIONAL__NO_OF_PEOPLE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    showRegionEClass.getESuperTypes().add(this.getQuery());
    findtempBuilActionEClass.getESuperTypes().add(this.getQuery());
    caltreesBuildActionEClass.getESuperTypes().add(this.getQuery());
    designResidentialEClass.getESuperTypes().add(this.getQuery());
    findtempDemolishEClass.getESuperTypes().add(this.getQuery());
    findtempPlantTreesEClass.getESuperTypes().add(this.getQuery());
    findtempCutTreesEClass.getESuperTypes().add(this.getQuery());
    findtempPlantBushesEClass.getESuperTypes().add(this.getQuery());
    findtempRemoveBushesEClass.getESuperTypes().add(this.getQuery());
    findtempCreateLakeEClass.getESuperTypes().add(this.getQuery());
    findtempRemoveLakeEClass.getESuperTypes().add(this.getQuery());
    designCommercialEClass.getESuperTypes().add(this.getQuery());
    designEducationalEClass.getESuperTypes().add(this.getQuery());

    // Initialize classes and features; add operations and parameters
    initEClass(domainModelEClass, DomainModel.class, "DomainModel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDomainModel_Elements(), this.getModel(), null, "elements", null, 0, -1, DomainModel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(modelEClass, Model.class, "Model", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModel_Query(), this.getQuery(), null, "query", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(queryEClass, Query.class, "Query", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getQuery_Region(), ecorePackage.getEInt(), "region", null, 0, 1, Query.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(showRegionEClass, showRegion.class, "showRegion", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(findtempBuilActionEClass, findtempBuilAction.class, "findtempBuilAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getfindtempBuilAction_No_of_buildings(), ecorePackage.getEInt(), "no_of_buildings", null, 0, 1, findtempBuilAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getfindtempBuilAction_Length(), ecorePackage.getEInt(), "length", null, 0, 1, findtempBuilAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getfindtempBuilAction_Breadth(), ecorePackage.getEInt(), "breadth", null, 0, 1, findtempBuilAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getfindtempBuilAction_Height(), ecorePackage.getEInt(), "height", null, 0, 1, findtempBuilAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(caltreesBuildActionEClass, caltreesBuildAction.class, "caltreesBuildAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getcaltreesBuildAction_No_of_buildings(), ecorePackage.getEInt(), "no_of_buildings", null, 0, 1, caltreesBuildAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getcaltreesBuildAction_Length(), ecorePackage.getEInt(), "length", null, 0, 1, caltreesBuildAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getcaltreesBuildAction_Breadth(), ecorePackage.getEInt(), "breadth", null, 0, 1, caltreesBuildAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getcaltreesBuildAction_Height(), ecorePackage.getEInt(), "height", null, 0, 1, caltreesBuildAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(designResidentialEClass, DesignResidential.class, "DesignResidential", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDesignResidential_No_of_people(), ecorePackage.getEInt(), "no_of_people", null, 0, 1, DesignResidential.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(findtempDemolishEClass, findtempDemolish.class, "findtempDemolish", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getfindtempDemolish_No_of_buildings(), ecorePackage.getEInt(), "no_of_buildings", null, 0, 1, findtempDemolish.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getfindtempDemolish_Length(), ecorePackage.getEInt(), "length", null, 0, 1, findtempDemolish.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getfindtempDemolish_Breadth(), ecorePackage.getEInt(), "breadth", null, 0, 1, findtempDemolish.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getfindtempDemolish_Height(), ecorePackage.getEInt(), "height", null, 0, 1, findtempDemolish.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(findtempPlantTreesEClass, findtempPlantTrees.class, "findtempPlantTrees", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getfindtempPlantTrees_No_of_trees(), ecorePackage.getEInt(), "no_of_trees", null, 0, 1, findtempPlantTrees.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(findtempCutTreesEClass, findtempCutTrees.class, "findtempCutTrees", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getfindtempCutTrees_No_of_trees(), ecorePackage.getEInt(), "no_of_trees", null, 0, 1, findtempCutTrees.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(findtempPlantBushesEClass, findtempPlantBushes.class, "findtempPlantBushes", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getfindtempPlantBushes_Area(), ecorePackage.getEInt(), "area", null, 0, 1, findtempPlantBushes.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(findtempRemoveBushesEClass, findtempRemoveBushes.class, "findtempRemoveBushes", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getfindtempRemoveBushes_Area(), ecorePackage.getEInt(), "area", null, 0, 1, findtempRemoveBushes.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(findtempCreateLakeEClass, findtempCreateLake.class, "findtempCreateLake", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getfindtempCreateLake_Area(), ecorePackage.getEInt(), "area", null, 0, 1, findtempCreateLake.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(findtempRemoveLakeEClass, findtempRemoveLake.class, "findtempRemoveLake", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getfindtempRemoveLake_Area(), ecorePackage.getEInt(), "area", null, 0, 1, findtempRemoveLake.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(designCommercialEClass, DesignCommercial.class, "DesignCommercial", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDesignCommercial_No_of_people(), ecorePackage.getEInt(), "no_of_people", null, 0, 1, DesignCommercial.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(designEducationalEClass, DesignEducational.class, "DesignEducational", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDesignEducational_No_of_people(), ecorePackage.getEInt(), "no_of_people", null, 0, 1, DesignEducational.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //FpPackageImpl
