/**
 * generated by Xtext 2.18.0
 */
package org.xtext.fp.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.fp.FpPackage;
import org.xtext.fp.showRegion;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>show Region</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class showRegionImpl extends QueryImpl implements showRegion
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected showRegionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FpPackage.Literals.SHOW_REGION;
  }

} //showRegionImpl
